language: php

php:
   - '5.6'
   - '7.0'

notifications:
   email:
      - stu@automattic.com

env:
   global:
      secure: cCRoX/FRQbt33L/cSMDXvuZA0VE8EjPOoHo1is791Bv01meh8qjqmNh9Vb7x6hKpD4xYtDhUoJXHm7xiQ9G8R+oyS+xcnCyWdRXOo+Fof2uG98MI6VCDH/UnIN1Rs3jCTpxigPO94x8z4CM8I31ALhGfhiGq3Rqu1vFOdtS4XpY=

after_success:
   - if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh generate-docs.sh; fi
